name: chat_flow
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_database: ^11.1.0

  # Arquitetura & Util
  provider: ^6.1.2
  intl: ^0.19.0
  google_fonts: ^6.2.1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo_splash.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: assets/logo_splash.png
  min_sdk_android: 21

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logo_splash.png
  android: true
  ios: true

  android_gravity: center

  android_12:
    color: "#FFFFFF"
    image: assets/logo_splash.png
